name: "ecommerce_demo"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "ecommerce_spark"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configs
models:
  ecommerce_demo:
    +schema: dbt_models
    +file_format: iceberg
    # Athena adapter
    +table_type: iceberg
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table

snapshots:
  ecommerce_demo:
    +file_format: iceberg

seeds:
  ecommerce_demo:
    +schema: raw_data
    +file_format: iceberg
