name: Setup
description: Checkout code, setup Python, install Poetry, and cache dependencies
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Configure poetry
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
        poetry config installer.max-workers 4

    - name: Cache poetry and virtualenv
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      shell: bash
      run: |
        poetry install --no-interaction --no-ansi
